displayName: Agente de Suporte de TI
schemaName: new_AgentedeSuportedeTI
accessControlPolicy: GroupMembership
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  settings:
    GenerativeActionsEnabled: false

  gPTSettings:
    defaultSchemaName: new_AgentedeSuportedeTI.gpt.default

  aISettings:
    useModelKnowledge: false
    isFileAnalysisEnabled: false
    isSemanticSearchEnabled: false
    contentModeration: Low
    optInUseLatestModels: false

template: o365LicenseRestrictedAgent-1.0.0
language: 1046